FROM balenalib/%%BALENA_ARCH%%-alpine

RUN set -eu && install_packages openssh-client jq dbus \
    && mkdir -p /root/.ssh \
    && ([ -f /run/secrets/id_ed25519 ] && cat < /run/secrets/id_ed25519 > /root/.ssh/id_ed25519) \
    && ([ -f /root/.ssh/id_ed25519 ] && chmod 600 /root/.ssh/id_ed25519)

COPY balena.sh /usr/local/bin/

CMD [ "balena.sh" ]
