---
name: deploy with balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, amd64]

    steps:
      - uses: actions/checkout@v2

      - id: staging-release
        uses: balena-io/balena-ci@master
        with:
          balena_token: ${{ secrets.STAGING_BALENA_API_KEY }}
          cache: false
          environment: balena-staging.com
          fleet: balena_os/cloud-config-${{ matrix.arch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true

      - id: production-release
        uses: balena-io/balena-ci@master
        with:
          balena_token: ${{ secrets.PRODUCTION_BALENA_API_KEY }}
          cache: false
          fleet: balena_os/cloud-config-${{ matrix.arch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true
